name: IT Hub Workflow with Testing

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq fzf

      - name: Setup IT Hub Environment
        env:
          ENV_FILE: /mnt/d/TROOP/.env
        run: |
          echo "Setting up the IT Hub environment..."
          # Ensure the script is executable
          chmod +x ./it_hub.sh
          # Export a dummy .env for testing purposes (replace with secrets in production)
          echo "MYSQL_SERVER_NAME=test-mysql" > /mnt/d/TROOP/.env
          echo "MYSQL_LOCATION=eastus2" >> /mnt/d/TROOP/.env
          echo "MYSQL_SERVER_EDITION=GeneralPurpose" >> /mnt/d/TROOP/.env
          echo "MYSQL_VCORES=1" >> /mnt/d/TROOP/.env
          echo "MYSQL_STORAGE_SIZE=20" >> /mnt/d/TROOP/.env
          echo "MYSQL_ADMIN_USERNAME=TestUser" >> /mnt/d/TROOP/.env
          echo "MYSQL_ADMIN_PASSWORD=TestPass123!" >> /mnt/d/TROOP/.env
          echo "RESOURCE_GROUP=IT-Hub-Test" >> /mnt/d/TROOP/.env
          echo "CLIENT_IP=0.0.0.0" >> /mnt/d/TROOP/.env

      - name: Test IT Hub Script
        env:
          ENV_FILE: /mnt/d/TROOP/.env
        run: |
          echo "Running IT Hub tests..."

          # Test listing resources
          ./it_hub.sh list all

          # Test deploying MySQL
          ./it_hub.sh deploy mysql

          # Test viewing deployed MySQL details
          ./it_hub.sh view mysql test-mysql

          # Test deleting MySQL server
          ./it_hub.sh delete mysql test-mysql

          # Re-run resource listing to confirm deletion
          ./it_hub.sh list all

      - name: Deploy Production Resources
        if: success()
        env:
          ENV_FILE: /mnt/d/TROOP/.env
        run: |
          echo "Deploying production resources..."
          ./it_hub.sh deploy mysql

      - name: Post-Deployment Logs and Validation
        run: |
          echo "Reviewing logs and validating deployment..."
          cat /mnt/d/TROOP/it_hub.log

      - name: List Final Deployed Resources
        run: |
          ./it_hub.sh list all
