name: IT Hub Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-and-test:
    name: Setup and Test IT Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq fzf

      - name: Setup IT Hub Environment
        run: |
          echo "Configuring IT Hub environment..."
          chmod +x ./it_hub.sh
          mkdir -p /mnt/d/TROOP
          cat <<EOL > /mnt/d/TROOP/.env
MYSQL_SERVER_NAME=test-mysql
MYSQL_LOCATION=eastus
MYSQL_SERVER_EDITION=GeneralPurpose
MYSQL_VCORES=1
MYSQL_STORAGE_SIZE=20
MYSQL_ADMIN_USERNAME=TestUser
MYSQL_ADMIN_PASSWORD=TestPass123!
MYSQL_DATABASE_NAME=TestDB
CLIENT_IP=0.0.0.0
RESOURCE_GROUP=IT-Hub-Test
EOL

      - name: Validate Script
        run: |
          echo "Validating script syntax..."
          bash -n ./it_hub.sh

      - name: Test Core Functions
        run: |
          echo "Testing core IT Hub functions..."
          ./it_hub.sh list resource-group
          ./it_hub.sh set-resource-group IT-Hub-Test
          ./it_hub.sh deploy mysql
          ./it_hub.sh view mysql test-mysql
          ./it_hub.sh delete mysql test-mysql
          ./it_hub.sh delete-resource-group IT-Hub-Test

      - name: Review Logs
        run: |
          echo "Reviewing logs for test run..."
          cat /mnt/d/TROOP/it_hub.log

  deploy-production:
    name: Deploy Production Resources
    runs-on: ubuntu-latest
    needs: setup-and-test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq fzf

      - name: Deploy Resources
        run: |
          echo "Deploying production resources..."
          ./it_hub.sh deploy mysql

      - name: Post-Deployment Validation
        run: |
          echo "Validating deployment..."
          ./it_hub.sh list all
          cat /mnt/d/TROOP/it_hub.log
